# Generated by Django 4.0.6 on 2022-08-24 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('debut', models.DateTimeField()),
                ('country', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='genre',
            name='name',
        ),
        migrations.AddField(
            model_name='genre',
            name='title',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
